# Generated by Django 3.2.9 on 2021-12-09 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0004_auto_20211209_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
    ]
