# Generated by Django 3.2.9 on 2021-12-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0005_remove_concertmodel_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'این سانس کنسل شده است'), (4, 'در حال فروش  بلیط')], verbose_name='وضعیت'),
        ),
    ]
